"""initial_postgres

Revision ID: 54b235f2912a
Revises: 
Create Date: 2024-11-22 22:10:00.023285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b235f2912a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('pl_mod', sa.String(length=255), nullable=True),
    sa.Column('modd', sa.String(length=255), nullable=True),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('booking_no', sa.String(length=100), nullable=True),
    sa.Column('booking_status', sa.String(length=50), nullable=True),
    sa.Column('bl_no', sa.String(length=100), nullable=True),
    sa.Column('bl_status', sa.String(length=50), nullable=True),
    sa.Column('doc_link', sa.String(length=255), nullable=True),
    sa.Column('cnt_no', sa.String(length=100), nullable=True),
    sa.Column('unit_m3', sa.Float(), nullable=True),
    sa.Column('noc', sa.Integer(), nullable=True),
    sa.Column('line', sa.String(length=255), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('cut_date', sa.Date(), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('vessel', sa.String(length=255), nullable=True),
    sa.Column('voyage', sa.String(length=50), nullable=True),
    sa.Column('pol', sa.String(length=100), nullable=True),
    sa.Column('pod', sa.String(length=100), nullable=True),
    sa.Column('p_base_bof', sa.Float(), nullable=True),
    sa.Column('p_bof', sa.Float(), nullable=True),
    sa.Column('p_crs', sa.Float(), nullable=True),
    sa.Column('p_cdd', sa.Float(), nullable=True),
    sa.Column('p_thc', sa.Float(), nullable=True),
    sa.Column('p_seal', sa.Float(), nullable=True),
    sa.Column('p_doc_star', sa.Float(), nullable=True),
    sa.Column('p_doc', sa.Float(), nullable=True),
    sa.Column('p_others', sa.Float(), nullable=True),
    sa.Column('p_taxable_ttl', sa.Float(), nullable=True),
    sa.Column('p_vat', sa.Float(), nullable=True),
    sa.Column('p_exvat_ttl', sa.Float(), nullable=True),
    sa.Column('p_pay_ttl', sa.Float(), nullable=True),
    sa.Column('s_inv_date', sa.Date(), nullable=True),
    sa.Column('s_inv_no', sa.String(length=100), nullable=True),
    sa.Column('s_link', sa.String(length=255), nullable=True),
    sa.Column('days', sa.String(length=50), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('usd_ex', sa.Float(), nullable=True),
    sa.Column('eur_ex', sa.Float(), nullable=True),
    sa.Column('r_base_bof', sa.Float(), nullable=True),
    sa.Column('r_bof', sa.Float(), nullable=True),
    sa.Column('r_crs', sa.Float(), nullable=True),
    sa.Column('r_cdd', sa.Float(), nullable=True),
    sa.Column('r_thc', sa.Float(), nullable=True),
    sa.Column('r_seal', sa.Float(), nullable=True),
    sa.Column('r_doc', sa.Float(), nullable=True),
    sa.Column('r_others', sa.Float(), nullable=True),
    sa.Column('r_taxable_ttl', sa.Float(), nullable=True),
    sa.Column('r_vat', sa.Float(), nullable=True),
    sa.Column('r_exvat_ttl', sa.Float(), nullable=True),
    sa.Column('r_adjustments', sa.Float(), nullable=True),
    sa.Column('rec_ttl', sa.Float(), nullable=True),
    sa.Column('c_inv_date', sa.Date(), nullable=True),
    sa.Column('c_inv_no', sa.String(length=100), nullable=True),
    sa.Column('c_link', sa.String(length=255), nullable=True),
    sa.Column('rec_date', sa.Date(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
