from sqlalchemy import Column, Integer, String, Date, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Client(Base):
    __tablename__ = 'clients'

    client_id = Column(Integer, primary_key=True, index=True)
    no = Column(Integer)
    name = Column(String(255), nullable=False)
    customer_code = Column(String(50), nullable=False, unique=True)
    address = Column(String(255))
    tel = Column(String(50))
    fax = Column(String(50))
    email = Column(String(255))


class Booking(Base):
    __tablename__ = 'bookings'

    booking_id = Column(Integer, primary_key=True, index=True)
    no = Column(Integer)
    pl_mod = Column(String(255))
    modd = Column(String(255))
    shipper = Column(String(255))
    customer_code = Column(String(50))
    booking_no = Column(String(100))
    booking_status = Column(String(50))
    bl_no = Column(String(100))
    bl_status = Column(String(50))
    doc_link = Column(String(255))
    cnt_no = Column(String(100))
    unit_m3 = Column(Float)
    noc = Column(Integer)
    line = Column(String(255))
    open_date = Column(Date, nullable=True)
    cut_date = Column(Date, nullable=True)
    etd = Column(Date, nullable=True)
    eta = Column(Date, nullable=True)
    vessel = Column(String(255))
    voyage = Column(String(50))
    pol = Column(String(100))
    pod = Column(String(100))
    p_base_bof = Column(Float)
    p_bof = Column(Float)
    p_crs = Column(Float)
    p_cdd = Column(Float)
    p_thc = Column(Float)
    p_seal = Column(Float)
    p_doc_star = Column(Float)
    p_doc = Column(Float)
    p_others = Column(Float)
    p_taxable_ttl = Column(Float)
    p_vat = Column(Float)
    p_exvat_ttl = Column(Float)
    p_pay_ttl = Column(Float)
    s_inv_date = Column(Date)
    s_inv_no = Column(String(100))
    s_link = Column(String(255))
    days = Column(String(50))
    pay_date = Column(Date)
    usd_ex = Column(Float)
    eur_ex = Column(Float)
    r_base_bof = Column(Float)
    r_bof = Column(Float)
    r_crs = Column(Float)
    r_cdd = Column(Float)
    r_thc = Column(Float)
    r_seal = Column(Float)
    r_doc = Column(Float)
    r_others = Column(Float)
    r_taxable_ttl = Column(Float)
    r_vat = Column(Float)
    r_exvat_ttl = Column(Float)
    r_adjustments = Column(Float)
    rec_ttl = Column(Float)
    c_inv_date = Column(Date)
    c_inv_no = Column(String(100))
    c_link = Column(String(255))
    rec_date = Column(Date)
    profit = Column(Float)

